package de.tomalbrc.skillcore.api;

public enum SkillTrigger {
    ON_COMBAT, // legacy onSpawn/despawn/unload/attack
    ON_ATTACK,
    ON_DAMAGED,
    ON_SPAWN,
    ON_DESPAWN,
    ON_READY, // ON_FIRST_SPAWN
    ON_LOAD,
    ON_SPAWN_OR_LOAD,
    ON_DEATH,
    ON_TIMER,
    ON_INTERACT,
    ON_PLAYER_KILL,
    ON_ENTER_COMBAT,
    ON_DROP_COMBAT,
    ON_CHANGE_TARGET,
    ON_EXPLODE,
    ON_PRIME,
    ON_CREEPER_CHARGE,
    ON_TELEPORT,
    ON_SIGNAL,
    ON_SHOOT, // onBowShoot   onShootBow
    ON_BOW_HIT,
    ON_TAME,
    ON_BREED,
    ON_TRADE,
    ON_CHANGE_WORLD,
    ON_BUCKET, // onUseBucket   onFillBucket   onBucketFill   onMilk   onMilked
    ON_SKILL_DAMAGE,
    ON_HEAR,
    ON_PROJECTILE_HIT,
    ON_PROJECTILE_LAND,

    // Player specifics
    ON_USE,
    ON_CANCEL_USE,
    ON_CONSUME /*ON_EAT*/,
    ON_CROUCH,
    ON_UNCROUCH,
    ON_EQUIP,
    ON_UNEQUIP,
    // ON_INTERACT for player
    ON_ITEM_DROP,
    ON_ITEM_PICKUP,
    ON_POTION_SPLASH,
    ON_RIGHT_CLICK,
    ON_SWING,
    ON_FISH,
    ON_FISH_BITE,
    ON_FISH_CATCH,
    ON_FISH_GRAB,
    ON_FISH_GROUND,
    ON_FISH_REEL,
    ON_FISH_FAIL,
    ON_PRESS_Q,
    ON_PRESS_CTRL_Q,
    ON_PRESS_F,
    ON_PRESS_F_HAND,
    ON_PRESS_F_OFFHAND,
    ON_JOIN,
    ON_RESPAWN,
    ON_PICKUP,
    ON_HOLD,
    ON_UN_HELD,
    ON_JUMP,
    // onPaint?
    ON_KILL,
    ON_KILL_PLAYER,
    ON_PROJECTILE_THROW,
    ON_START_DESTROY_BLOCK,
    ON_STOP_DESTROY_BLOCK
}
